### ISSUE TITLE
where is the nginx.conf

### ISSUE THREAD

**Issue by worldwar** [NYTimes/nginx-vod-module-docker#2]
Can you submit a nginx.conf file as an example to config video files location, encoder & resolution and other options? Thanks!

**Comment by fsouza** [comment]
Hi @worldwar, thanks for opening this issue. Our exact configuration is not public, but I've created a PR with an example configuration: https://github.com/NYTimes/nginx-vod-module-docker/pull/3.

Please let me know if that helps.
