### ISSUE TITLE
/thumb/ does not work

### ISSUE THREAD

**Issue by icamys** [NYTimes/nginx-vod-module-docker#8]
I am running the [example](https://github.com/NYTimes/nginx-vod-module-docker/tree/master/examples#hls--dash-example) and getting following nginx error:

```
2018/02/13 17:08:35 [error] 6#6: *1 open() "/opt/static/html/thumb/devito360p.mp4/thumb-1000.jpg" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /thumb/devito360p.mp4/thumb-1000.jpg HTTP/1.1", host: "localhost:3030"
172.17.0.1 - [13/Feb/2018:17:08:35 +0000] "GET /thumb/devito360p.mp4/thumb-1000.jpg HTTP/1.1" 404 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36"
```

**Comment by fsouza** [comment]
Het @icamys, thanks for opening this issue.

Can you double check that you have the latest version of the example folder cloned locally? Or can you share the contents of the ``nginx.conf`` file you're using locally along with the ``docker run`` line you're using?

**Comment by icamys** [comment]
Sorry, my bad! I actually was using an old version of dockerfile. Thank you for your help!

**Comment by fsouza** [comment]
Awesome, thanks for confirming!
